org.gradle.jvmargs=-Xmx1536m -Dfile.encoding=UTF-8 -Djava.net.preferIPv4Stack=true -Dorg.gradle.internal.http.connectionTimeout=30000 -Dorg.gradle.internal.http.socketTimeout=30000 -Dorg.gradle.internal.repository.max.retries=5 -Dorg.gradle.internal.repository.retry.wait=1000
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.workers.max=4
kotlin.compiler.execution.strategy=in-process
android.aapt2FromMavenOverride=/usr/bin/aapt2
